// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:02c1626c-5127-48d5-8320-9c4095aa3828",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_AtDu630Hd",
    "aws_user_pools_web_client_id": "3dgffav9vg3hfvm6m85oqi7cuc",
    "oauth": {},
    "predictions": {
        "convert": {
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Joanna",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
